// ui/src/Views/Account.tsx
import { Avatar, Button, Paper, Table, Text } from "@mantine/core";
import userEvent from "@testing-library/user-event";
import { IdTokenClaims, User } from "oidc-client-ts";
import { useEffect, useState } from "react";
import { userManager } from "../userManager";

function Account() {
  const [user, setAccount] = useState<IdTokenClaims | null>(null)

  useEffect(() => {
    (async () => {
    const oidcUser = await userManager.getUser()
    setAccount(oidcUser?.profile ?? null)
  })()
  }, [])

  return (
    <>
      <Paper p="xl">
        <h1>Account</h1>
        <Table>
          <tbody>
            <tr>
              <td>
                Username
              </td>
              <td>
                {user?.preferred_username}
              </td>
            </tr>
            <tr>
              <td>
                Email
              </td>
              <td>
                {user?.email}
              </td>
            </tr>
          </tbody>
        </Table>
        <Text sx={{ margin: "25px 0 25px 0", maxWidth: 800}}>
          <p>
            Your account is used for logging into UCC Netsoc web services
          </p>
          <p>
            Please remember to keep the Terms of Use and its Acceptable Use Policy in mind as you share server hardware with our other users.
          </p>
        </Text>

        <nav style={{ maxWidth: 600, display: "flex", alignItems: "center", justifyContent: "space-evenly"}}>
          <Button color="orange.6">
            Reset Password
          </Button>
          <Button color="yellow.6">
            Request GDPR Data
          </Button>
          <Button color="red.6">
            Delete Account
          </Button>
        </nav>
      </Paper>
    </>
  )
}

export default Account;

// ui/src/views/Account.vue
<template>
  <v-container fluid>
    <v-row>
      <v-col cols="12" sm="6">
        <v-card>
          <v-card-title>
            Hi {{ $store.state.auth.user.profile.preferred_username }}!
          </v-card-title>
          <v-card-subtitle>
            UCC Netsoc welcomes you!
          </v-card-subtitle>
          <v-card-text class="ma-0 justify-center">
            Username: <span class="white--text text--lighten-1">{{ $store.state.auth.user.profile.preferred_username }}</span><br/>
            Email: <span class="white--text text--lighten-1">{{ $store.state.auth.user.profile.email }}</span><br/>
            <br/>
            <p>
              Your account is used for logging into UCC Netsoc web services
              <br/>
              Please remember to keep the <b>Terms of Use</b> and its <b>Acceptable Use Policy</b> in mind as you share server hardware with our other users.
            </p>
            <v-btn color="warning" class="mx-1" @click="passwordReset.visible=true">
              Reset Password
            </v-btn>
            <v-btn color="primary" class="mx-1" @click="gdprRequest.visible=true">
              Data Request
            </v-btn>
            <v-btn color="red" class="mx-1" @click="deleteAccount.visible=true">
              Delete Account
            </v-btn>
          </v-card-text>
        </v-card>
      </v-col>
    </v-row>
    <password-reset-dialog :visible="passwordReset.visible" @successful="passwordReset.visible=false" @cancelled="passwordReset.visible=false"/>
    <g-d-p-r-dialog :visible="gdprRequest.visible" @successful="gdprRequest.visible=false" @cancelled="gdprRequest.visible=false"/>
    <delete-account-dialog :visible="deleteAccount.visible" @successful="deleteAccount.visible=false"/>
  </v-container>
</template>

<script lang="ts">
import Vue from 'vue'
import PasswordResetDialog from '@/components/PasswordResetDialog.vue'
import GDPRDialog from '@/components/GDPRDialog.vue'
import DeleteAccountDialog from '@/components/DeleteAccountDialog.vue'

export default Vue.extend({
  name: 'Account',
  components: {
    PasswordResetDialog,
    GDPRDialog,
    DeleteAccountDialog
  },

  data: () => ({
    passwordReset: {
      visible: false
    },

    gdprRequest: {
      visible: false
    },

    deleteAccount: {
      visible: false
    }
  })
})
</script>
